import { Exercise } from '../types';

export const EXERCISES: Exercise[] = [
  // ─── CORE ───────────────────────────────────────────────────
  {
    id: 'the-hundred',
    name: 'Yüzler',
    description:
      'Pilates\'in simgesi olan ısınma hareketidir. Kolların ritmik yukarı-aşağı hareketi derin karın kaslarını aktive ederken nefes kontrolü sağlar. Bacaklar masa üstü pozisyonunda ya da uzatılmış şekilde havada tutulur.',
    muscleGroups: ['Düz Karın Kası', 'Enine Karın Kası', 'Kalça Fleksörleri'],
    level: 'Beginner',
    bodyArea: 'Core',
    sets: 1,
    reps: '100 tekrar',
    durationSeconds: 60,
    instructions: [
      'Sırtüstü uzan, dizleri masa üstü pozisyonunda bük; baldırlar yere paralel olsun.',
      'Baş, boyun ve omuzları minderden kaldır; gözler dizlere yönelsin.',
      'Kolları yanlara uzat, minderden birkaç santimetre yukarıda tut.',
      'Beş harekette nefes al, beş harekette nefes ver.',
      'Kolların hareketi küçük ve ritmik olsun; karın merkezini omurgaya doğru çek.',
      'On nefes döngüsü tamamlayarak toplamda yüz tekrara ulaş.',
    ],
    tips: [
      'Bel omurgasını hareket boyunca mindere bastır.',
      'İleri düzey: daha fazla zorluk için bacakları kırk beş dereceye uzat.',
    ],
    aiImagePrompt: 'woman performing Pilates hundred exercise, lying on mat, legs at table-top, arms pumping, soft studio light',
  },
  {
    id: 'roll-up',
    name: 'Yuvarlanarak Kalkış',
    description:
      'Karın kaslarını güçlendiren ve omurga esnekliğini artıran yavaş, eklemli bir omurga yuvarlanmasıdır. On mekiğe bedeldir.',
    muscleGroups: ['Düz Karın Kası', 'Omurga Ekstansörleri', 'Kalça Fleksörleri'],
    level: 'Intermediate',
    bodyArea: 'Core',
    sets: 3,
    reps: '8',
    instructions: [
      'Sırtüstü uzan, bacaklar birleşik ve uzatılmış, kollar başın üzerinde uzanmış.',
      'Nefes al; kolları tavana doğru kaldırırken çeneyi göğse doğru yuvarla.',
      'Omurgayı minderden omur omur soyarak oturmaya devam et.',
      'Üstte parmaklarını ayaklarına doğru uzan; derin bir hamstring gerimi hisset.',
      'Nefes al; kontrollü biçimde geri yat.',
    ],
    tips: ['Yavaş gitmek daha zordur — ivme kullanma isteğine karşı dur.'],
    aiImagePrompt: 'woman performing Pilates roll-up, seated forward with arms reaching to toes, elegant studio',
  },
  {
    id: 'single-leg-stretch',
    name: 'Tek Bacak Germe',
    description:
      'Karın kaslarını çapraz koordinasyon modeliyle zorlayan dönüşümlü bacak uzatma hareketidir.',
    muscleGroups: ['Enine Karın Kası', 'Yan Karın Kasları', 'Kalça Fleksörleri'],
    level: 'Beginner',
    bodyArea: 'Core',
    sets: 3,
    reps: '10 her tarafa',
    instructions: [
      'Sırtüstü uzan, her iki dizi de göğse çek; baş ve omuzlar minderden kalkık olsun.',
      'Sağ dizi göğse doğru çek; sağ eli bileğe, sol eli dize koy.',
      'Sol bacağı eş zamanlı olarak kırk beş dereceye uzat.',
      'Kontrollü şekilde bacakları değiştir: sağ bacak uzarken sol içeri çekilir.',
      'Nefes ritmi: iki değişimde nefes al, iki değişimde nefes ver.',
    ],
    aiImagePrompt: 'woman doing Pilates single leg stretch on yoga mat, one leg extended, graceful movement',
  },
  {
    id: 'double-leg-stretch',
    name: 'Çift Bacak Germe',
    description:
      'Kolları ve bacakları merkezden uzaklaştırıp geri bir araya getiren güçlü bir merkez hareketidir.',
    muscleGroups: ['Düz Karın Kası', 'Enine Karın Kası', 'Omuz Stabilizatörleri'],
    level: 'Intermediate',
    bodyArea: 'Core',
    sets: 3,
    reps: '10',
    instructions: [
      'Sırtüstü uzan, her iki dizi de karnına çek; baş ve omuzlar minderden kalkık olsun.',
      'Nefes al: kolları başın üzerine, bacakları kırk beş dereceye uzat.',
      'Nefes ver: kolları dairesel hareketle geri getir, dizleri karnına çek.',
      'Uzanma boyunca bel omurgasını sıkıca mindere bastır.',
    ],
    aiImagePrompt: 'woman doing double leg stretch Pilates, limbs extended, arched gracefully on mat',
  },
  {
    id: 'criss-cross',
    name: 'Çapraz Mekik',
    description:
      'Yan karın kaslarını hedef alan döndürme hareketidir. Düz ve güçlü bir belin temel egzersizlerindendir.',
    muscleGroups: ['İç Yan Karın Kasları', 'Dış Yan Karın Kasları', 'Düz Karın Kası'],
    level: 'Intermediate',
    bodyArea: 'Core',
    sets: 3,
    reps: '10 her tarafa',
    instructions: [
      'Sırtüstü uzan, elleri başın arkasında; her iki bacak masa üstü pozisyonunda.',
      'Baş ve omuzları minderden kaldır.',
      'Nefes al; sağ bacağı uzatırken sol omuzu sağ dize doğru döndür.',
      'Dönüşü tam bir nefes boyunca tut, ardından taraf değiştir.',
      'Boynu çekme; karın kaslarının çalışmasına izin ver.',
    ],
    aiImagePrompt: 'woman doing Pilates criss-cross oblique exercise, rotated upper body, mat workout',
  },
  {
    id: 'leg-circles',
    name: 'Bacak Çemberleri',
    description:
      'Pelvis tamamen hareketsizken bir bacağın kalça ekleminde büyük daireler çizdiği kontrol hareketidir.',
    muscleGroups: ['Kalça Fleksörleri', 'Kalça Abduktörleri', 'Enine Karın Kası'],
    level: 'Intermediate',
    bodyArea: 'Core',
    sets: 3,
    reps: '5 daire her yönde',
    instructions: [
      'Sırtüstü uzan, sağ bacak tavana uzatılmış; sol bacak minderde uzun.',
      'Kollar yanlarda, denge için mindere bas.',
      'Sağ bacağı hafifçe vücudun üzerinden geçir; aşağı, yana ve başlangıç noktasına dön.',
      'Pelvisin kesinlikle kımıldamamasına dikkat et; sağa sola sallanma.',
      'Beş daire tamamla, ardından yönü tersine çevir.',
    ],
    aiImagePrompt: 'woman doing Pilates leg circles lying on mat, one leg raised to ceiling, controlled movement',
  },

  // ─── BACK ────────────────────────────────────────────────────
  {
    id: 'swan',
    name: 'Kuğu',
    description:
      'Göğsü açan, omurga ekstansörlerini güçlendiren ve uzun süreli oturmanın etkilerini dengeleyen sırt uzatma hareketidir.',
    muscleGroups: ['Omurga Dikeltici Kaslar', 'Romboid Kaslar', 'Kalça Kasları'],
    level: 'Intermediate',
    bodyArea: 'Back',
    sets: 3,
    reps: '8',
    instructions: [
      'Yüz üstü uzan, eller omuzların altında; dirsekler kaburga kafasına yakın.',
      'Nefes al; omurgayı nazik bir yay içinde uzatarak yukarı bas.',
      'Karın kaslarını aktif tut: sırttan kaldır, yalnızca kollarla değil.',
      'Üstte iki sayı tut, ardından yavaşça in.',
      'Boynu korumak için yukarıya değil, öne bak.',
    ],
    tips: ['Başının tepesini öne ve yukarıya doğru çeken bir ip hayal et.'],
    aiImagePrompt: 'woman performing Swan Pilates back extension on mat, elegant spine arc, soft natural light',
  },
  {
    id: 'swimming',
    name: 'Yüzme',
    description:
      'Tüm arka zinciri güçlendiren, yüz üstü pozisyonunda dönüşümlü kol ve bacak kaldırma hareketidir.',
    muscleGroups: ['Omurga Dikeltici Kaslar', 'Kalça Kasları', 'Arka Uyluk Kasları', 'Omuz Stabilizatörleri'],
    level: 'Advanced',
    bodyArea: 'Back',
    sets: 3,
    reps: '30s',
    durationSeconds: 30,
    instructions: [
      'Yüz üstü uzan, kollar ve bacaklar uzatılmış.',
      'Her iki kol ve bacağı minderden hafifçe kaldır.',
      'Dönüşümlü hareket et: sağ kol ile sol bacak yükselirken sol kol ile sağ bacak iner.',
      'Beş sayı nefes al, beş sayı nefes ver; ritmi koru.',
      'Hareket boyunca karın kaslarını minderden kaldırılmış tut.',
    ],
    aiImagePrompt: 'woman doing Pilates swimming exercise prone on mat, opposite limbs lifted, strong back',
  },
  {
    id: 'cat-cow',
    name: 'Kedi–İnek',
    description:
      'Sırtı ısıtan, gerginliği gideren ve omurga mobilitesini artıran nazif bir omurga dalgası hareketidir.',
    muscleGroups: ['Omurga Dikeltici Kaslar', 'Multifidus', 'Düz Karın Kası'],
    level: 'Beginner',
    bodyArea: 'Back',
    sets: 2,
    reps: '10 döngü',
    instructions: [
      'El ve dizler üzerinde başla; bilekler omuzların, dizler kalçaların altında.',
      'Nefes al: karnı mindere doğru bırak, göğüs ve kuyruk kemiği yukarı kalksın. Bu İnek pozisyonu.',
      'Nefes ver: omurgayı tavana doğru yuvarlat, çene ve pelvis içeri gelsin. Bu Kedi pozisyonu.',
      'Yavaş hareket et ve her pozisyonda tam nefes al.',
    ],
    aiImagePrompt: 'woman doing cat-cow stretch on yoga mat, spine arching and rounding, warm studio',
  },
  {
    id: 'spine-stretch',
    name: 'Omurga Germe',
    description:
      'Omurgayı uzatan, arka uyluk kaslarını germeye yarayan ve derin karın kaslarını çalıştıran oturarak öne eğilme hareketidir.',
    muscleGroups: ['Omurga Dikeltici Kaslar', 'Arka Uyluk Kasları', 'Enine Karın Kası'],
    level: 'Beginner',
    bodyArea: 'Back',
    sets: 3,
    reps: '8',
    instructions: [
      'Dik otur, bacaklar kalça genişliğinde açık ve uzatılmış; ayaklar gergin.',
      'Kolları omuz hizasında öne uzat.',
      'Nefes ver: omurgayı C eğrisi yaparak öne eğil, baş dizlere doğru gitsin.',
      'Nefes al ve omurgayı omur omur doğrult, dik otur.',
    ],
    aiImagePrompt: 'woman doing Pilates spine stretch forward, seated reaching toward feet, long spine',
  },

  // ─── LEGS ────────────────────────────────────────────────────
  {
    id: 'bridge',
    name: 'Köprü',
    description:
      'Kalça kaslarını, arka uyluk kaslarını ve merkezi güçlendiren temel Pilates hareketidir. Bel ağrısı için de oldukça faydalıdır.',
    muscleGroups: ['Kalça Kasları', 'Arka Uyluk Kasları', 'Enine Karın Kası', 'Omurga Dikeltici Kaslar'],
    level: 'Beginner',
    bodyArea: 'Legs',
    sets: 3,
    reps: '10',
    instructions: [
      'Sırtüstü uzan, dizler bükülü; ayak tabanları yerde, kalça genişliğinde açık.',
      'Kollar yanlarda, avuç içleri yere baksın.',
      'Nefes al; nefes vererek kalçaları yavaşça minderden kaldır.',
      'Diz, kalça ve omuzlar düz bir çizgi oluştursun.',
      'Üstte iki sayı tut; nefes alarak yavaşça geri in.',
    ],
    tips: ['Kalçaları kaldırırken karın kaslarını içe çek ve sık.'],
    aiImagePrompt: 'woman doing Pilates bridge exercise, hips lifted, feet flat on mat, strong glutes',
  },
  {
    id: 'side-kick',
    name: 'Yan Tekme',
    description:
      'Kalça abdüktörlerini ve stabilitatörlerini çalıştıran, merkez gücünü test eden yan yatış hareketidir.',
    muscleGroups: ['Kalça Abduktörleri', 'Kalça Kasları', 'Enine Karın Kası'],
    level: 'Intermediate',
    bodyArea: 'Legs',
    sets: 3,
    reps: '10 her tarafa',
    instructions: [
      'Yan yat, vücut düz bir çizgide; alt eli başın altında, üst eli önünde minderde.',
      'Üst bacağı kalça hizasına kaldır.',
      'Nefes al: üst bacağı öne doğru götür.',
      'Nefes ver: bacağı kontrollü şekilde geri getir.',
      'Hareket boyunca pelvisin sabit kalmasına dikkat et.',
    ],
    aiImagePrompt: 'woman doing Pilates side kick exercise on mat, leg swinging forward with energy',
  },
  {
    id: 'pilates-squat',
    name: 'Pilates Çömelme',
    description:
      'Topuklar kalkık ve omurga uzatılmış pozisyonda yapılan derin çömelme hareketidir. Ön uyluk gücü ve denge geliştirir.',
    muscleGroups: ['Ön Uyluk Kasları', 'Kalça Kasları', 'Baldır Kasları', 'Merkez Kaslar'],
    level: 'Intermediate',
    bodyArea: 'Legs',
    sets: 3,
    reps: '12',
    instructions: [
      'Ayaklar kalça genişliğinde aç; parmak uçları kırk beş derece dışarıya dönük.',
      'Topukları kaldır ve ayak tabanında dengelen.',
      'Nefes al ve derin çömelmeye in; diz kapakları ayak parmaklarının üzerine gelsin.',
      'Hareket boyunca omurgayı uzun ve göğsü dik tut.',
      'Nefes vererek ayağa kalk. Setler arasında topukları yere indir.',
    ],
    aiImagePrompt: 'woman doing Pilates squat with heels raised, elegant posture, studio background',
  },
  {
    id: 'scissors',
    name: 'Makas',
    description:
      'Aynı anda güçlü karın kontrolü ve esneklik gerektiren ileri düzey bacak hareketi.',
    muscleGroups: ['Arka Uyluk Kasları', 'Kalça Fleksörleri', 'Enine Karın Kası'],
    level: 'Advanced',
    bodyArea: 'Legs',
    sets: 3,
    reps: '8 her tarafa',
    instructions: [
      'Sırtüstü uzan, her iki bacak tavana uzatılmış; baş ve omuzlar minderden kaldırılmış.',
      'Sağ bacağı her iki elle tut ve sol bacağı kırk beş dereceye indir.',
      'Sağ bacağı yüze doğru nazikçe iki kez esnet.',
      'Bacakları değiştir: sol bacak yüze, sağ bacak uzanır.',
      'Merkezi sıkı tut; boynu çekme.',
    ],
    aiImagePrompt: 'woman doing Pilates scissors exercise, both legs in air at different angles, intense core work',
  },

  // ─── FULL BODY ───────────────────────────────────────────────
  {
    id: 'rolling-like-a-ball',
    name: 'Top Gibi Yuvarlanma',
    description:
      'Denge ve karın kontrolü geliştirirken sırt gerginliğini gideren, omurga için masaj etkisi yaratan harekettir.',
    muscleGroups: ['Düz Karın Kası', 'Omurga Fleksörleri', 'Kalça Fleksörleri'],
    level: 'Beginner',
    bodyArea: 'Full Body',
    sets: 3,
    reps: '8',
    instructions: [
      'Minderin önüne otur, dizleri göğse çek; elleri bileklere koy.',
      'Ayakları minderden kaldır, kuyruk kemiği üzerinde dengelen.',
      'Omurgayı C eğrisi şeklinde yuvarlat; çene göğse değsin.',
      'Nefes al ve omuz küreklerine kadar geri yuvarlan. Boyuna kadar gitme!',
      'Nefes ver ve başlangıç dengesine geri yuvarlan.',
    ],
    tips: ['Hiçbir zaman boyuna yuvarlanma; omuz küreklerinde dur.'],
    aiImagePrompt: 'woman rolling like a ball in Pilates, perfectly rounded back, balancing, studio mat',
  },
  {
    id: 'teaser',
    name: 'Teaser',
    description:
      'Mat Pilates\'in zirvesi sayılan bu hareket; tam merkez kontrolü, güç ve koordinasyon gerektiren V dengesidir.',
    muscleGroups: ['Düz Karın Kası', 'Kalça Fleksörleri', 'Omurga Ekstansörleri', 'Omuz Stabilizatörleri'],
    level: 'Advanced',
    bodyArea: 'Full Body',
    sets: 3,
    reps: '5',
    instructions: [
      'Sırtüstü uzan, kollar başın üzerinde uzatılmış; bacaklar birleşik.',
      'Nefes al; nefes vererek kolları ve bacakları eş zamanlı kaldırarak kuyruk kemiği üzerinde dengelen.',
      'Vücut V şekli oluştursun: bacaklar kırk beş derecede, kollar bacaklara paralel.',
      'Kontrollü biçimde iki sayı dengede kal.',
      'Nefes al; nefes vererek yavaşça geri yat.',
    ],
    aiImagePrompt: 'woman doing Pilates Teaser exercise, V-shape balance on tailbone, elegant studio photo',
  },
  {
    id: 'plank',
    name: 'Pilates Plank',
    description:
      'Merkez stabilitesi, omuz gücü ve vücut hizasını aynı anda geliştiren tam vücut izometrik tutuş hareketidir.',
    muscleGroups: ['Enine Karın Kası', 'Omuz Stabilizatörleri', 'Kalça Kasları', 'Ön Uyluk Kasları'],
    level: 'Intermediate',
    bodyArea: 'Full Body',
    sets: 3,
    reps: '30s',
    durationSeconds: 30,
    instructions: [
      'Şınav pozisyonunda başla: eller omuzların altında, vücut baştan topuğa düz bir çizgide.',
      'Karın kaslarını içe çek, kalça kaslarını hafifçe sıkıştır.',
      'Kalçaları düz tut: ne çök ne de yukarı kalk.',
      'Süre boyunca düzenli nefes al; bakış eller arasına.',
      'Gerekirse dizleri yere koyarak hareketi kolaylaştırabilirsin.',
    ],
    aiImagePrompt: 'woman holding Pilates plank position on mat, perfect alignment, focused expression',
  },
  {
    id: 'saw',
    name: 'Testere',
    description:
      'Yan karın kaslarını güçlendirirken omurga, arka uyluk ve kalçaları germeye yarayan oturarak dönüş hareketidir.',
    muscleGroups: ['Yan Karın Kasları', 'Arka Uyluk Kasları', 'Omurga Dikeltici Kaslar', 'Kalça Rotasyon Kasları'],
    level: 'Intermediate',
    bodyArea: 'Full Body',
    sets: 3,
    reps: '6 her tarafa',
    instructions: [
      'Dik otur, bacaklar kalçadan geniş açık; kollar omuz hizasında yanlara uzatılmış.',
      'Nefes al, omurgayı uzat ve gövdeyi sağa döndür.',
      'Nefes ver: sol eli sağ ayak parmağına doğru ulaştır.',
      'Arka kol kaldırılır ve döner; üç kez ileri uzanma hareketi yap.',
      'Nefes al ve merkeze dön; sola tekrarla.',
    ],
    aiImagePrompt: 'woman doing the Saw exercise in Pilates, twisted forward toward foot, arms wide, mat class',
  },
  {
    id: 'spine-twist',
    name: 'Omurga Dönüşü',
    description:
      'Omurgadaki gerginliği gideren ve döndürme gücü oluşturan oturarak dönüş hareketidir.',
    muscleGroups: ['Yan Karın Kasları', 'Omurga Dikeltici Kaslar', 'Kalça Stabilizatörleri'],
    level: 'Intermediate',
    bodyArea: 'Full Body',
    sets: 3,
    reps: '8 her tarafa',
    instructions: [
      'Oturma kemikleri üzerinde dik otur, bacaklar birleşik ve uzatılmış; ayaklar gergin.',
      'Kollar omuz hizasında yanlara uzatılmış, avuç içleri aşağı.',
      'Nefes al ve omurgayı uzat; nefes vererek iki kısa dönüş hareketiyle sağa dön.',
      'Kalçaların sıkıca yere basmasına ve öne bakmasına dikkat et.',
      'Merkeze dön, ardından sola tekrarla.',
    ],
    aiImagePrompt: 'woman doing spine twist seated Pilates exercise, arms wide, elegant rotation',
  },
  {
    id: 'mermaid',
    name: 'Denizkızı Germe',
    description:
      'Yan vücudu açan, omuz mobilitesini geliştiren ve gerginliği gideren güzel bir yan esneme hareketidir.',
    muscleGroups: ['Yan Karın Kasları', 'Latissimus Dorsi', 'Ara Kaburga Kasları', 'Omuz'],
    level: 'Beginner',
    bodyArea: 'Full Body',
    sets: 2,
    reps: '5 her tarafa',
    instructions: [
      'Bacakları sola katlanmış şekilde otur.',
      'Sol el yanında minderde; sağ kol başın üzerine uzanmış.',
      'Nefes al; nefes vererek sağa eğil ve sol tarafın açıldığını hisset.',
      'Nefes al ve dik pozisyona dön; karşı tarafı germek için sağ kolu yukarı ve üzerine uzat.',
      'Tüm tekrarları tamamladıktan sonra taraf değiştir.',
    ],
    aiImagePrompt: 'woman doing Pilates mermaid stretch, arms arched overhead gracefully, serene studio',
  },
  {
    id: 'pilates-pushup',
    name: 'Pilates Şınavı',
    description:
      'Ayakta duruştan aşağı yuvarlanan ve şınav çeken, tüm vücudu bütünleşik çalıştıran ileri düzey harekettir.',
    muscleGroups: ['Göğüs Kasları', 'Triceps', 'Omuz Stabilizatörleri', 'Enine Karın Kası'],
    level: 'Advanced',
    bodyArea: 'Full Body',
    sets: 3,
    reps: '5',
    instructions: [
      'Minderin tepesinde dik dur.',
      'Nefes al; nefes vererek aşağı yuvarlan ve elleri plank pozisyonuna doğru ilerlet.',
      'Dirsekler kaburga kafasına yakın olacak şekilde üç şınav çek.',
      'Elleri ayaklara geri yürüt; dizleri hafif bükük tut.',
      'Omur omur ayağa kalk.',
    ],
    aiImagePrompt: 'woman doing Pilates push-up after roll-down, in plank lowering gracefully, dynamic shot',
  },
];

// Helper maps for quick access
export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e])
);
